import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Template NextJs</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <h1>Olá mundo</h1>
      </main>
    </div>
  );
}
